version: '3.8'
services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sistema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata: